use dbx_plugin_sdk::{
    PluginEmitter, PluginError, PluginHandler, PluginMetadata, PluginServer, RequestContext,
};
use serde_json::{json, Value};
use std::time::{SystemTime, UNIX_EPOCH};

struct Plugin;

fn tool_list() -> Value {
    json!({"tools": [{
        "name": "generate_mock_insert_sql",
        "description": "根据 MySQL 表名、字段名和字段类型生成 INSERT SQL。只生成 SQL 文本，不写入数据库；如需写入，请使用 DBX 自带 dbx_execute_query 工具以遵循 DBX MCP 权限。",
        "annotations": {"readOnlyHint": true},
        "inputSchema": {
            "type": "object",
            "properties": {
                "connectionId": {"type": "string", "description": "由 DBX MCP 注入的连接"},
                "database": {"type": "string"},
                "table": {"type": "string"},
                "row_count": {"type": "integer", "minimum": 1, "maximum": 500},
                "columns": {"type": "array", "items": {"type": "object", "properties": {
                    "name": {"type": "string"}, "type": {"type": "string"},
                    "nullable": {"type": "boolean"}, "auto_increment": {"type": "boolean"},
                    "generated": {"type": "boolean"}, "comment": {"type": "string"},
                    "enum_values": {"type": "array", "items": {"type": "string"}}
                }, "required": ["name", "type"]}}
            },
            "required": ["connectionId", "database", "table", "columns", "row_count"]
        }
    }]})
}

impl PluginHandler for Plugin {
    fn handle(
        &self,
        _context: RequestContext,
        method: &str,
        params: Value,
        _emitter: &PluginEmitter,
    ) -> Result<Value, PluginError> {
        match method {
            "mcp/tools" => Ok(tool_list()),
            "mcp/call" => {
                if params.get("tool").and_then(Value::as_str) != Some("generate_mock_insert_sql") {
                    return Err(PluginError::new(-32602, "Unknown MCP tool"));
                }
                match generate_sql(&params.get("arguments").cloned().unwrap_or(Value::Null)) {
                    Ok(sql) => {
                        Ok(json!({"content": [{"type": "text", "text": sql}], "isError": false}))
                    }
                    Err(message) => {
                        Ok(json!({"content": [{"type": "text", "text": message}], "isError": true}))
                    }
                }
            }
            _ => Err(PluginError::method_not_found(method)),
        }
    }
}

fn generate_sql(args: &Value) -> Result<String, String> {
    let database = args["database"]
        .as_str()
        .filter(|s| !s.is_empty())
        .ok_or("database is required")?;
    let table = args["table"]
        .as_str()
        .filter(|s| !s.is_empty())
        .ok_or("table is required")?;
    let count = args["row_count"]
        .as_u64()
        .filter(|n| (1..=500).contains(n))
        .ok_or("row_count must be 1-500")? as usize;
    let source = args["columns"]
        .as_array()
        .ok_or("columns must be an array")?;
    let columns: Vec<&Value> = source
        .iter()
        .filter(|column| {
            column["name"].as_str().is_some_and(|name| !name.is_empty())
                && column["auto_increment"] != true
                && column["generated"] != true
        })
        .collect();
    if columns.is_empty() {
        return Err("table has no writable columns".into());
    }

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos() as u64;
    let mut random = Random(now);
    let names = columns
        .iter()
        .map(|column| ident(column["name"].as_str().unwrap()))
        .collect::<Vec<_>>()
        .join(", ");
    let rows = (0..count)
        .map(|row| {
            let values = columns
                .iter()
                .map(|column| make_value(column, row, &mut random))
                .collect::<Vec<_>>()
                .join(", ");
            format!("  ({values})")
        })
        .collect::<Vec<_>>()
        .join(",\n");
    Ok(format!("-- Generated by DBX MySQL Mock Data MCP. Review constraints and foreign keys before execution.\nINSERT INTO {}.{} ({names})\nVALUES\n{rows};", ident(database), ident(table)))
}

struct Random(u64);
impl Random {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }
    fn pick(&mut self, n: usize) -> usize {
        (self.next() as usize) % n.max(1)
    }
}

fn make_value(column: &Value, row: usize, random: &mut Random) -> String {
    let name = column["name"].as_str().unwrap_or("value");
    let field = name.to_lowercase();
    let kind = column["type"].as_str().unwrap_or("varchar").to_lowercase();
    if column["nullable"] == true && random.pick(20) == 0 {
        return "NULL".into();
    }
    if let Some(values) = column["enum_values"]
        .as_array()
        .filter(|values| !values.is_empty())
    {
        return literal(
            values[random.pick(values.len())]
                .as_str()
                .unwrap_or("unknown"),
        );
    }
    if [
        "create",
        "created",
        "update",
        "updated",
        "modify",
        "modified",
        "gmt_create",
        "gmt_modified",
    ]
    .iter()
    .any(|part| field.contains(part))
        && ["date", "time", "timestamp"]
            .iter()
            .any(|part| kind.contains(part))
    {
        return if kind.starts_with("date") && !kind.contains("datetime") {
            "CURRENT_DATE"
        } else {
            "CURRENT_TIMESTAMP"
        }
        .into();
    }
    if ["int", "year", "bool", "bit"]
        .iter()
        .any(|part| kind.starts_with(part))
    {
        if ["id", "count", "quantity", "num"]
            .iter()
            .any(|part| field.contains(part))
        {
            return (row + 1).to_string();
        }
        return random.pick(100).to_string();
    }
    if ["decimal", "numeric", "float", "double"]
        .iter()
        .any(|part| kind.starts_with(part))
    {
        return format!("{:.2}", random.pick(100000) as f64 / 100.0);
    }
    if kind.starts_with("date") {
        return "CURRENT_DATE".into();
    }
    if kind.contains("time") {
        return "CURRENT_TIMESTAMP".into();
    }
    if field.contains("email") {
        return literal(&format!("user{}@example.test", row + 1));
    }
    if field.contains("phone") || field.contains("mobile") {
        return literal(&format!("138{:08}", random.pick(100000000)));
    }
    if field.contains("name") {
        return literal(&format!("Mock User {}", row + 1));
    }
    literal(&format!("mock_{}_{}", name, row + 1))
}

fn ident(value: &str) -> String {
    format!("`{}`", value.replace('`', "``"))
}
fn literal(value: &str) -> String {
    format!("'{}'", value.replace('\\', "\\\\").replace('\'', "''"))
}

fn main() -> std::io::Result<()> {
    let metadata = PluginMetadata::new("io.github.kute.mysql-mock-data", env!("CARGO_PKG_VERSION"));
    PluginServer::new(metadata, Plugin).serve()
}

#[cfg(test)]
mod tests {
    use super::{generate_sql, ident, literal, tool_list};
    use serde_json::json;

    fn args(columns: serde_json::Value, row_count: u64) -> serde_json::Value {
        json!({
            "connectionId": "test-connection",
            "database": "test_db",
            "table": "users",
            "row_count": row_count,
            "columns": columns
        })
    }

    #[test]
    fn generates_requested_number_of_rows_and_field_values() {
        let sql = generate_sql(&args(
            json!([
                {"name": "id", "type": "int", "auto_increment": true},
                {"name": "email", "type": "varchar(255)"},
                {"name": "created_at", "type": "datetime"}
            ]),
            2,
        ))
        .unwrap();

        assert!(sql.contains("INSERT INTO `test_db`.`users` (`email`, `created_at`)"));
        assert!(sql.contains("'user1@example.test', CURRENT_TIMESTAMP"));
        assert!(sql.contains("'user2@example.test', CURRENT_TIMESTAMP"));
        assert_eq!(sql.matches("\n  (").count(), 2);
    }

    #[test]
    fn excludes_generated_columns_and_uses_enum_values() {
        let sql = generate_sql(&args(
            json!([
                {"name": "computed", "type": "varchar(20)", "generated": true},
                {"name": "status", "type": "enum", "enum_values": ["ready", "paused"]}
            ]),
            1,
        ))
        .unwrap();

        assert!(!sql.contains("computed"));
        assert!(sql.contains("(`status`)"));
        assert!(sql.contains("'ready'") || sql.contains("'paused'"));
    }

    #[test]
    fn escapes_identifiers_and_string_literals() {
        assert_eq!(ident("odd`name"), "`odd``name`");
        assert_eq!(literal("O'Reilly\\seed"), "'O''Reilly\\\\seed'");
    }

    #[test]
    fn rejects_missing_fields_empty_tables_and_out_of_range_counts() {
        assert_eq!(
            generate_sql(&json!({})).unwrap_err(),
            "database is required"
        );
        assert_eq!(
            generate_sql(&args(json!([]), 1)).unwrap_err(),
            "table has no writable columns"
        );
        assert_eq!(
            generate_sql(&args(json!([{"name":"name","type":"varchar"}]), 0)).unwrap_err(),
            "row_count must be 1-500"
        );
        assert_eq!(
            generate_sql(&args(json!([{"name":"name","type":"varchar"}]), 501)).unwrap_err(),
            "row_count must be 1-500"
        );
    }

    #[test]
    fn exposes_read_only_mcp_tool_metadata() {
        let tool = &tool_list()["tools"][0];
        assert_eq!(tool["name"], "generate_mock_insert_sql");
        assert_eq!(tool["annotations"]["readOnlyHint"], true);
        assert_eq!(
            tool["inputSchema"]["properties"]["row_count"]["maximum"],
            500
        );
    }
}
